[env]
WORKSPACE_PATH = { script = ["pwd"] }
API_SPEC_PATH = "doc/specifications/api_v1.yml"
ROOT_SPEC_PATH = "doc/specifications/root.yml"
API_CODEGEN_PATH = "crates/client/src/codegen.rs"
ROOT_CODEGEN_PATH = "crates/client/src/root_codegen.rs"
end_point_port = "8080"
# local 開発用のデータベースURLです。 shuttle が勝手に docker 起動してくれる.
# port は `cargo shuttle run` した時に決まります。
DATABASE_URL = "postgres://postgres:postgres@localhost:21735/postgres"
API_URL = "http://localhost:8080"

[config]
default_to_workspace = false

# -- common
[tasks.format]
command = "cargo"
args = ["fmt", "--", "--emit=files", "${@}" ]

[tasks.clippy]
command = "cargo"
args = ["clippy", "${@}" ]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.my-flow]
dependencies = [
    "format",
    "clippy",
]

# -- tools
[tasks.tools]
command = "cargo"
args = ["run", "--release", "--package", "rust-study-tools", "${@}"]

# -- frontend
[tasks.build-yew]
command = "trunk"
args = [ "build", "./crates/front/index.html", "--release", "--dist", "${WORKSPACE_PATH}/dist" ]
dependencies = [ "install-trunk", "install-wasm" ]

[tasks.install-trunk]
command = "cargo"
args = [ "install", "trunk" ]

[tasks.install-wasm]
command = "cargo"
args = [ "install", "wasm-bindgen-cli" ]

# -- backend
[tasks.run]
command = "cargo"
args = [ "shuttle", "run", "--port", "${end_point_port}" ]

[tasks.sqlx]
command = "sqlx"
args = [ "${@}" ]
dependencies = [ "install-sqlx-cli" ]

[tasks.install-sqlx-cli]
command = "cargo"
args = [ "install", "sqlx-cli", "--no-default-features", "--features", "native-tls,postgres" ]
