openapi: 3.0.3
info:
  title: rust-study-server
  description: Rust study web application
  contact:
    name: rust4fun
  license:
    name: ''
  version: 0.1.0
paths:
  /api/v1/articles:
    get:
      tags:
      - articles
      operationId: list
      responses:
        '200':
          description: get article records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
    post:
      tags:
      - articles
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
        required: true
      responses:
        '200':
          description: create article record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
  /api/v1/articles/{id}:
    get:
      tags:
      - articles
      operationId: get_item
      parameters:
      - name: id
        in: path
        description: article id
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: get article record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
components:
  schemas:
    Article:
      type: object
      required:
      - id
      - url
      - image_url
      properties:
        description:
          type: string
          nullable: true
        id:
          type: string
          format: uuid
        image_url:
          type: string
        title:
          type: string
          nullable: true
        url:
          type: string
    RequestBody:
      type: object
      required:
      - url
      properties:
        url:
          type: string
tags:
- name: api
