[package]
name = "rust-study-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
uuid = { workspace = true, features = [ "v4", "serde" ] }
utoipa = { workspace = true }
