name: Shuttle Deploy

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install npm    
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
  
    - name: Build css  
      run: | 
        npm install
        npm run build

    - name: Install trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
  
    - name: Build frontend
      run: |
        rustup target add wasm32-unknown-unknown
        AUTH_URL=${{ vars.AUTH_URL }} API_URL=${{ vars.API_URL }} \
          trunk build ./crates/front/index.html --release --dist ${WORKSPACE_PATH}/dist

    - name: Deploy shuttle
      uses: shuttle-hq/deploy-action@main
      with:
        deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
        allow-dirty: "true"
        no-test: "true"
        cargo-shuttle-version: "0.39.0"
        secrets: |
          AUTH_SECRET = '${{ secrets.AUTH_SECRET }}'
          DB_SECRET = '${{ secrets.DB_SECRET }}'
