name: Shuttle Deploy

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy shuttle
      uses: shuttle-hq/deploy-action@main
      with:
        deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
