name: Shuttle Deploy

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add build target
      run: rustup target add wasm32-unknown-unknown

    - name: Install cargo-make
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-make

    - name: Build frontend
      # TODO: ここの環境変数の渡し方がめんどくさい
      run: |
        AUTH_URL=${{ vars.AUTH_URL }} API_URL=${{ vars.API_URL }} cargo make build-yew

    - name: Deploy shuttle
      uses: shuttle-hq/deploy-action@main
      with:
        deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
        allow-dirty: "true"
        no-test: "true"
        secrets: |
          AUTH_SECRET = "${{ secrets.AUTH_SECRET }}"
          DB_SECRET = "${{ secrets.DB_SECRET }}"
