name: Shuttle Deploy

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install cargo-make
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-make

    - name: Install cargo-make
      uses: baptiste0928/cargo-install@v2
      with:
        crate: trunk

    - name: Build frontend
      uses: actions/checkout@v4
    - run: cargo make build-yew

    - name: Deploy shuttle
      uses: shuttle-hq/deploy-action@main
      with:
        deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
